<?php
/**
 * File: EmptyController.class.php
 * User: xieguoqiu
 * Date: 2016/5/19 11:33
 */

namespace Common\Common\Controller;


class EmptyController extends BaseController
{
    public function _empty()
    {
        parent::_empty('错误操作'); // TODO: Change the autogenerated stub
    }
}
 